doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            transaction_id: App\Shared\Transaction\Infrastructure\Persistence\Doctrine\TransactionIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Transaction:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Transaction/Infrastructure/Persistence/Doctrine'
                prefix: App\Core\Transaction\Domain\Model
                alias: Transaction
