doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            transaction_id: App\Infrastructure\Transaction\Persistence\Doctrine\TransactionIdType
            bank_account_id: App\Infrastructure\BankAccount\Persistence\Doctrine\BankAccountIdType
            bank_account_type: App\Infrastructure\BankAccount\Persistence\Doctrine\BankAccountTypeType
            bank_account_activity_type: App\Infrastructure\BankAccount\Persistence\Doctrine\BankAccountActivityTypeType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Transaction:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Transaction/Persistence/Doctrine'
                prefix: App\Core\Transaction\Domain\Model
                alias: Transaction
            BankAccount:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/BankAccount/Persistence/Doctrine'
                prefix: App\Core\BankAccount\Domain\Model
                alias: BankAccount
