framework:
    messenger:
        # The bus that is going to be injected when injecting MessageBusInterface
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
            event.bus.async:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            App\Infrastructure\Bus\AsyncEvent\AsyncEventHandlerInterface: async