parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/*/DependencyInjection/'
            - '../src/*/Domain/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\UserInterface\WebSite\Transaction\Action\:
        resource: '../src/UserInterface/WebSite/Transaction/Action/'
        tags: [ 'controller.service_arguments']

    App\Core\Transaction\Domain\Repository\TransactionRepository: '@App\Core\Transaction\Infrastructure\Persistence\OrmTransactionRepository'
